# process schedule
# a list of several pai_rag offline process operators with their arguments
process:
  - op: "pai_rag_parser"
    oss_store:
      bucket: "pai-rag"
      endpoint: "oss-cn-hangzhou.aliyuncs.com"
    accelerator: "cpu"
    mem_required: "6GB"

  - op: "pai_rag_splitter"
    type: "Sentence"
    chunk_size: 800
    chunk_overlap: 20
    enable_multimodal: true

  - op: "pai_rag_embedder"
    source: "huggingface"
    model: "bge-large-zh-v1.5"
    enable_sparse: true
    enable_multimodal: true
    multimodal_source: "cnclip"
    accelerator: "cpu"
    mem_required: "8GB"
