experiment:
  # [custom knowledge dataset]
  - name: "exp1"
    data_path: "example_data/eval_docs_1"
    setting_file: "src/pai_rag/config/evaluation/settings_eval.toml"
    evaluator: pai
  # - name: "exp2"
  #   data_path: "example_data/eval_docs_1"
  #   setting_file: "src/pai_rag/config/evaluation/settings_eval.toml"
  #   evaluator: base
