experiment:
  # [custom knowledge dataset]
  - name: "exp1"
    eval_data_path: "example_data/eval_docs"
    eval_model_source: "Dashscope"
    eval_model_name: "qwen-max"
    rag_setting_file: "src/pai_rag/config/evaluation/settings_eval_for_text.toml"
  - name: "exp2"
    eval_data_path: "example_data/eval_docs_1"
    eval_model_source: "Dashscope"
    eval_model_name: "qwen-vl-max"
    rag_setting_file: "src/pai_rag/config/evaluation/settings_eval_for_image.toml"
