experiment:
  #   [custom knowledge dataset]
  - name: "exp1"
    eval_data_path: "example_data/eval_docs_text"
    eval_modal_llm:
      source: "dashscope"
      model: "qwen-max"
      max_tokens: 1024
    rag_setting_file: "src/pai_rag/config/evaluation/settings_eval_for_text.toml"
  - name: "exp2"
    eval_data_path: "example_data/eval_docs_text"
    eval_modal_llm:
      source: "dashscope"
      model: "qwen-max"
      max_tokens: 1024
    rag_setting_file: "src/pai_rag/config/evaluation/settings_eval_for_image.toml"
    tested_multimodal_llm:
      source: "dashscope"
      model: "qwen-vl-max"
      max_tokens: 1024
  - name: "exp3"
    qca_dataset_path: "data/eval_dataset/multimodal_eval_dataset_zh_example.json"
    eval_modal_llm:
      source: "dashscope"
      model: "qwen-max"
      max_tokens: 1024
    rag_setting_file: "src/pai_rag/config/evaluation/settings_eval_for_image.toml"
    tested_multimodal_llm:
      source: "dashscope"
      model: "qwen-vl-max"
      max_tokens: 1024
