#
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ["feature"]

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: registry.cn-beijing.aliyuncs.com
  REGISTRY_HZ: registry.cn-hangzhou.aliyuncs.com

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Login to ACR Beijing region
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Login to ACR Hangzhou region
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_HZ }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push base image
        env:
          IMAGE_TAG: 0.0.2
        run: |
          docker build -t ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG .
          docker tag ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG ${{ env.REGISTRY_HZ }}/mybigpai/pairag:$IMAGE_TAG
          docker push ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG
          docker push ${{ env.REGISTRY_HZ }}/mybigpai/pairag:$IMAGE_TAG

      - name: Build and push GPU image
        env:
          IMAGE_TAG: 0.0.2_gpu
        run: |
          docker build -t ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG -f Dockerfile_gpu .
          docker tag ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG ${{ env.REGISTRY_HZ }}/mybigpai/pairag:$IMAGE_TAG
          docker push ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG
          docker push ${{ env.REGISTRY_HZ }}/mybigpai/pairag:$IMAGE_TAG
